export const wordData = {
    "verbs": [
        {"kanji":"<ruby>会<rt>あ<\/rt></ruby>う","type":"u","eng":"to meet; to see (a person)"},
        {"kanji":"ある","type":"u","eng":"there is . . ."},
        {"kanji":"<ruby>行<rt>い<\/rt></ruby>く","type":"irv","eng":"to go","group":"iku"},
        {"kanji":"いる","type":"ru","eng":"(a person) is in . . . ; stays at . . ."},
        {"kanji":"<ruby>起<rt>お<\/rt></ruby>きる","type":"ru","eng":"to get up"},
        {"kanji":"<ruby>泳<rt>およ<\/rt></ruby>ぐ","type":"u","eng":"to swim"},
        {"kanji":"<ruby>買<rt>か<\/rt></ruby>う","type":"u","eng":"to buy"},
        {"kanji":"<ruby>帰<rt>かえ<\/rt></ruby>る","type":"u","eng":"to go back; to return"},
        {"kanji":"<ruby>書<rt>か<\/rt></ruby>く","type":"u","eng":"to write"},
        {"kanji":"<ruby>聞<rt>き<\/rt></ruby>く","type":"u","eng":"to ask"},
        {"kanji":"<ruby>聞<rt>き<\/rt></ruby>く","type":"u","eng":"to listen; to hear"},
        {"kanji":"<ruby>来<rt>く<\/rt></ruby>る","type":"irv","eng":"to come"},
        {"kanji":"する","type":"irv","eng":"to do","group":"suru"},
        {"kanji":"<ruby>食<rt>た<\/rt></ruby>べる","type":"ru","eng":"to eat"},
        {"kanji":"<ruby>出<rt>で<\/rt></ruby>かける","type":"ru","eng":"to go out"},
        {"kanji":"<ruby>撮<rt>と<\/rt></ruby>る","type":"u","eng":"to take (a picture)"},
        {"kanji":"<ruby>寝<rt>ね<\/rt></ruby>る","type":"ru","eng":"to sleep; to go to sleep"},
        {"kanji":"<ruby>飲<rt>の<\/rt></ruby>む","type":"u","eng":"to drink"},
        {"kanji":"<ruby>乗<rt>の<\/rt></ruby>る","type":"u","eng":"to ride; to board"},
        {"kanji":"<ruby>話<rt>はな<\/rt></ruby>す","type":"u","eng":"to speak; to talk"},
        {"kanji":"<ruby>勉強<\/ruby>する","type":"irv","eng":"to study"},
        {"kanji":"<ruby>待<rt>ま<\/rt></ruby>つ","type":"u","eng":"to wait"},
        {"kanji":"<ruby>見<rt>み<\/rt></ruby>る","type":"ru","eng":"to see; to look at; to watch"},
        {"kanji":"やる","type":"u","eng":"to do; to perform"},
        {"kanji":"<ruby>読<rt>よ<\/rt></ruby>む","type":"u","eng":"to read"},
        {"kanji":"わかる","type":"u","eng":"to understand"}
    ],
    "adjectives": [
        {"kanji":"おいしい","type":"i","eng":"delicious"},
        {"kanji":"<ruby>高<rt>たか<\/rt></ruby>い","type":"i","eng":"expensive; high"},
        {"kanji":"いい","type":"i","eng":"good"},
        {"kanji":"<ruby>早<rt>はや<\/rt></ruby>い","type":"i","eng":"early"},
        {"kanji":"<ruby>新<rt>あたら<\/rt></ruby>しい","type":"i","eng":"new"},
        {"kanji":"<ruby>熱<rt>あつ<\/rt></ruby>い","type":"i","eng":"hot (thing)"},
        {"kanji":"<ruby>暑<rt>あつ<\/rt></ruby>い","type":"i","eng":"hot (weather)"},
        {"kanji":"<ruby>忙<rt>いそが<\/rt></ruby>しい","type":"i","eng":"busy (people/days)"},
        {"kanji":"<ruby>大<rt>おお<\/rt></ruby>きい","type":"i","eng":"large"},
        {"kanji":"<ruby>面白<rt>おもしろ<\/rt></ruby>い","type":"i","eng":"interesting; funny"},
        {"kanji":"かっこいい","type":"i","eng":"good-looking"},
        {"kanji":"<ruby>嫌<rt>きら<\/rt></ruby>い","type":"na","eng":"disgusted with; to dislike"},
        {"kanji":"きれい","type":"na","eng":"beautiful; clean"},
        {"kanji":"<ruby>元気<rt>げんき<\/rt></ruby>","type":"na","eng":"healthy; energetic"},
        {"kanji":"<ruby>怖<rt>こわ<\/rt></ruby>い","type":"i","eng":"frightening"},
        {"kanji":"<ruby>寒<rt>さむ<\/rt></ruby>い","type":"i","eng":"cold (weather)"},
        {"kanji":"<ruby>静<rt>しず<\/rt></ruby>か","type":"na","eng":"quiet"},
        {"kanji":"<ruby>好<rt>す<\/rt></ruby>き","type":"na","eng":"fond of; to like"},
        {"kanji":"<ruby>大嫌<rt>だいきら<\/rt></ruby>い","type":"na","eng":"to hate"},
        {"kanji":"<ruby>大好<rt>だいす<\/rt></ruby>き","type":"na","eng":"very fond of; to love"},
        {"kanji":"<ruby>楽<rt>たの<\/rt></ruby>しい","type":"i","eng":"fun"},
        {"kanji":"<ruby>小<rt>ちい<\/rt></ruby>さい","type":"i","eng":"small"},
        {"kanji":"つまらない","type":"i","eng":"boring"},
        {"kanji":"にぎやか","type":"na","eng":"lively"},
        {"kanji":"<ruby>暇<rt>ひま<\/rt></ruby>","type":"na","eng":"not busy; free (time)"},
        {"kanji":"<ruby>古<rt>ふる<\/rt></ruby>い","type":"i","eng":"old (thing)"},
        {"kanji":"<ruby>難<rt>むずか<\/rt></ruby>しい","type":"i","eng":"difficult"},
        {"kanji":"やさしい","type":"i","eng":"easy (problem); kind (person)"},
        {"kanji":"<ruby>安<rt>やす<\/rt></ruby>い","type":"i","eng":"inexpensive; cheap (thing)"}
    ]
}